/*
    ############################################################
    # DISCLAIMER:
    #
    # This Apex code is intended for EDUCATIONAL and PORTFOLIO
    # demonstration purposes only. It is not for resale, reuse,
    # or redistribution in commercial production environments.
    #
    # All logic, structure, and naming have been modified or
    # aliased to protect intellectual property and to reflect
    # safe, fictional use cases.
    #
    # The author assumes no responsibility for any misuse,
    # mishandling, or legal consequences resulting from the
    # use of this code in any unauthorized context.
    #
    # Author: Joven Caddauan
    ############################################################
*/
public without sharing class ConstantVariables {
    // Opportunity
    public class Opportunity{
        public static final String CLOSED_WON = 'Closed Won';
        public static final String RENEWAL = 'Prospecting';
        public static final String TYPE = 'Existing Customer - Replacement';
        public static final String RENEWAL_NAME = 'Renewal';
    }

    // Proposal
    public class Proposal{
        public static final String TYPE = 'Renewal';
    }
}